### ISSUE TITLE
Crashing Heroku Dyno while using Cloudinary Variables.

### ISSUE THREAD

**Issue by asharamseervi** [SNathJr/ghost2-on-heroku#1]
Hey @SNathJr ,
Greetings & thanking you for making this contribution to all of us.

I'm a little bit stuck b/w this repo (https://github.com/SNathJr/ghost2-on-heroku/) and the forked repo (https://github.com/SNathJr/ghost-on-heroku). I've not tested this repo (ghost2-on-heroku) but got to know only I want to raise an issue. _In short, which one should be preferred._

The issue is with Cloudinary. It crashes dyno whenever I update CLOUDINARY_CLOUD_ID, CLOUDINARY_API_KEY, and CLOUDINARY_API_SECRET in both ways, either inserting before deploy (via hardcoding) as well as Configuring Variables via Heroku dashboard. If I remove these variables, the dyno will do it function smoothly.

**Comment by asharamseervi** [comment]
Hello @SNathJr, Any updates?
Did you get into this?

**Comment by SNathJr** [comment]
Please refer to https://github.com/SNathJr/ghost-on-heroku for updates
